In [10]:
import pandas as pd
players_22 = pd.read_csv('players_22.csv', sep=',', na_values=[''], quotechar='"')
players_22

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16608\1397760884.py:2: DtypeWarning: Columns (0: nation_position, 1: nation_logo_url) have mixed types. Specify dtype option on import or set low_memory=False.
  players_22 = pd.read_csv('players_22.csv', sep=',', na_values=[''], quotechar='"')

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,170,72,73.0,Paris Saint-Germain,French Ligue 1,1.0,RW,30.0,NaN,2021-08-10,2023.0,52,Argentina,1369.0,RW,10.0,Left,4,4,5,Medium/Low,Unique,Yes,144300000.0,"#Dribbler, #Distance Shooter, #FK Specialist, ...","Finesse Shot, Long Shot Taker (AI), Playmaker ...",85.0,92.0,91.0,95.0,34.0,65.0,85,95,70,91,88,96,93,94,91,96,91,80,91,94,95,86,68,72,69,94,44,40,93,95,75,96,20,35,24,6,11,15,14,8,NaN,89+3,89+3,89+3,92,93,93,93,92,93,93,93,91+2,87+3,87+3,87+3,91+2,66+3,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,1988-08-21,185,81,21.0,FC Bayern München,German 1. Bundesliga,1.0,ST,9.0,NaN,2014-07-01,2023.0,37,Poland,1353.0,RS,9.0,Right,4,4,5,High/Medium,Unique,Yes,197200000.0,"#Aerial Threat, #Distance Shooter, #Clinical F...","Solid Player, Finesse Shot, Outside Foot Shot,...",78.0,92.0,79.0,86.0,44.0,82.0,71,95,90,85,89,85,79,85,70,88,77,79,77,93,82,90,85,76,86,87,81,49,95,81,90,88,35,42,19,15,6,12,8,10,NaN,90+2,90+2,90+2,85,88,88,88,85,86+3,86+3,86+3,84+3,80+3,80+3,80+3,84+3,64+3,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,187,83,11.0,Manchester United,English Premier League,1.0,ST,7.0,NaN,2021-08-27,2023.0,38,Portugal,1354.0,ST,7.0,Right,4,5,5,High/Low,Unique,Yes,83300000.0,"#Aerial Threat, #Dribbler, #Distance Shooter, ...","Power Free-Kick, Flair, Long Shot Taker (AI), ...",87.0,94.0,80.0,88.0,34.0,75.0,87,95,90,80,86,88,81,84,77,88,85,88,86,94,74,94,95,77,77,93,63,29,95,76,88,95,24,32,24,7,11,15,14,11,NaN,90+1,90+1,90+1,88,89,89,89,88,86+3,86+3,86+3,86+3,78+3,78+3,78+3,86+3,63+3,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,175,68,73.0,Paris Saint-Germain,French Ligue 1,1.0,LW,10.0,NaN,2017-08-03,2025.0,54,Brazil,NaN,NaN,NaN,Right,5,5,5,High/Medium,Unique,Yes,238700000.0,"#Speedster, #Dribbler, #Playmaker, #FK Special...","Injury Prone, Flair, Speed Dribbler (AI), Play...",91.0,83.0,86.0,94.0,37.0,63.0,85,83,63,86,86,95,88,87,81,95,93,89,96,89,84,80,64,81,53,81,63,37,86,90,93,93,35,32,29,9,9,15,15,11,NaN,83+3,83+3,83+3,90,88,88,88,90,89+2,89+2,89+2,89+2,82+3,82+3,82+3,89+2,67+3,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,181,70,10.0,Manchester City,English Premier League,1.0,RCM,17.0,NaN,2015-08-30,2025.0,7,Belgium,1325.0,RCM,7.0,Right,5,4,4,High/High,Unique,Yes,232200000.0,"#Dribbler, #Playmaker, #Engine, #Distance Shoo...","Injury Prone, Leadership, Early Crosser, Long ...",76.0,86.0,93.0,88.0,64.0,78.0,94,82,55,94,82,88,85,83,93,91,76,76,79,91,78,91,63,89,74,91,76,66,88,94,83,89,68,65,53,15,13,5,10,13,NaN,83+3,83+3,83+3,88,87,87,87,88,89+2,89+2,89+2,89+2,89+2,89+2,89+2,89+2,79+3,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,https://sofifa.com/player/261962/defu-song/220002,Song Defu,宋德福,CDM,47,52,70000.0,1000.0,22,1999-01-02,180,64,112541.0,Wuhan FC,Chinese Super League,1.0,SUB,36.0,NaN,2021-04-01,2021.0,155,China PR,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,114000.0,NaN,NaN,58.0,35.0,46.0,48.0,42.0,49.0,46,32,48,50,30,45,33,38,48,49,56,60,55,53,70,46,62,51,46,30,52,42,38,43,42,37,38,43,48,6,10,5,15,13,NaN,44+2,44+2,44+2,46,45,45,45,46,46+2,46+2,46+2,47+2,46+2,46+2,46+2,47+2,48+2,46+2,46+2,46+2,48+2,48+2,46+2,46+2,46+2,48+2,15+2,https://cdn.sofifa.net/players/261/962/22_120.png,https://cdn.sofifa.net/teams/112541/60.png,https://cdn.sofifa.net/flags/cn.png,NaN,https://cdn.sofifa.net/flags/cn.png
19235,262040,https://sofifa.com/player/262040/caoimhin-port...,C. Porter,Caoimhin Porter,CM,47,59,110000.0,500.0,19,2002-03-18,175,70,445.0,Derry City,Rep. Ireland Airtricity League,1.0,RES,27.0,NaN,2021-02-22,2021.0,25,Republic of Ireland,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,193000.0,NaN,NaN,59.0,39.0,50.0,46.0,41.0,51.0,54,33,46,51,32,41,53,31,50,42,60,58,64,49,69,49,47,63,47,38,49,39,51,49,44,47,37,44,47,11,12,6,8,10,NaN,45+2,45+2,45+2,47,46,46,46,47,47+2,47+2,47+2,49+2,47+2,47+2,47+2,49+2,49+2,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2,https://cdn.sofifa.net/players/262/040/22_120.png,https://cdn.sofifa.net/teams/445/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19236,262760,https://sofifa.com/player/262760/nathan-logue/...,N. Logue,Nathan Logue-Cunningham,CM,47,55,100000.0,500.0,21,2000-02-07,178,72,111131.0,Finn Harps,Rep. Ireland Airtricity League,1.0,RES,31.0,NaN,2021-06-18,2021.0,25,Republic of Ireland,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,175000.0,NaN,NaN,60.0,37.0,45.0,49.0,41.0,52.0,39,32,43,49,37,47,37,37,49,49,60,60,58,46,59,50,57,56,50,34,51,38,45,46,39,36,38,44,48,8,6,7,10,6,NaN,45+2,45+2,45+2,46,46,46,46,46,47+2,47+2,47+2,48+2,47+2,47+2,47+2,48+2,47+2,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2,https://cdn.sofifa.net/players/262/760/22_120.png,https://cdn.sofifa.net/teams/111131/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19237,262820,https://sofifa.com/player/262820/luke-rudden/2...,L. Rudden,Luke Rudden,ST,47,60,110000.0,500.0,19,2002-04-23,173,66,111131.0,Finn Harps,Rep. Ireland Airtricity League,1.0,RES,12.0,NaN,2021-06-18,2021.0,25,Republic of Ireland,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,239000.0,NaN,NaN,68.0,46.0,36.0,48.0,15.0,42.0,29,49,40,38,34,42,36,34,33,45,69,67,72,48,73,48,50,50,40,41,34,14,47,40,49,47,10,14,11,7,10,7,14,15,NaN,47+2,47+2,47+2,47,47,47,47,47,45+2,45+2,45+2,45+2,39+2,39+2,39+2,45+2,33+2,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2,https://cdn.sofifa.net/players/262/820/22_120.png,https://cdn.sofifa.net/teams/111131/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19238,264540,https://sofifa.com/player/264540/emanuel-lalch...,E. Lalchhanchhuaha,Emanuel Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,2002-02-06,167,61,113040.0,NorthEast United FC,Indian Super League,1.0,SUB,13.0,NaN,2021-08-31,2025.0,159,India,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-),No,217000.0,NaN,NaN,68.0,38.0,45.0,48.0,36.0,48.0,39,32,46,50,37,48,38,32,49,38,70,67,65,54,85,50,62,57,40,36,55,42,47,46,35,36,33,31,37,8,13,13,9,14,NaN,45+2,45+2,45+2,47,47,47,47,47,47+2,47+2,47+2,48+2,46+2,46+2,46+2,48+2,45+2,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2,https://cdn.sofifa.net/players/264/540/22_120.png,https://cdn.sofifa.net/teams/113040/60.png,https://cdn.sofifa.net/flags/in.png,NaN,https://cdn.sofifa.net/flags/in.png

In [14]:
players_22.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 110 columns):
 #    Column                       Non-Null Count  Dtype
---   ------                       --------------  -----
 0    sofifa_id                    19239 non-null  int64
 1    player_url                   19239 non-null  str
 2    short_name                   19239 non-null  str
 3    long_name                    19239 non-null  str
 4    player_positions             19239 non-null  str
 5    overall                      19239 non-null  int64
 6    potential                    19239 non-null  int64
 7    value_eur                    19165 non-null  float64
 8    wage_eur                     19178 non-null  float64
 9    age                          19239 non-null  int64
 10   dob                          19239 non-null  str
 11   height_cm                    19239 non-null  int64
 12   weight_kg                    19239 non-null  int64
 13   club_team_id                 19178 non-null  float64
 14   club_name                    19178 non-null  str
 15   league_name                  19178 non-null  str
 16   league_level                 19178 non-null  float64
 17   club_position                19178 non-null  str
 18   club_jersey_number           19178 non-null  float64
 19   club_loaned_from             1102 non-null   str
 20   club_joined                  18076 non-null  str
 21   club_contract_valid_until    19178 non-null  float64
 22   nationality_id               19239 non-null  int64
 23   nationality_name             19239 non-null  str
 24   nation_team_id               759 non-null    float64
 25   nation_position              759 non-null    str
 26   nation_jersey_number         759 non-null    float64
 27   preferred_foot               19239 non-null  str
 28   weak_foot                    19239 non-null  int64
 29   skill_moves                  19239 non-null  int64
 30   international_reputation     19239 non-null  int64
 31   work_rate                    19239 non-null  str
 32   body_type                    19239 non-null  str
 33   real_face                    19239 non-null  str
 34   release_clause_eur           18063 non-null  float64
 35   player_tags                  1441 non-null   str
 36   player_traits                9398 non-null   str
 37   pace                         17107 non-null  float64
 38   shooting                     17107 non-null  float64
 39   passing                      17107 non-null  float64
 40   dribbling                    17107 non-null  float64
 41   defending                    17107 non-null  float64
 42   physic                       17107 non-null  float64
 43   attacking_crossing           19239 non-null  int64
 44   attacking_finishing          19239 non-null  int64
 45   attacking_heading_accuracy   19239 non-null  int64
 46   attacking_short_passing      19239 non-null  int64
 47   attacking_volleys            19239 non-null  int64
 48   skill_dribbling              19239 non-null  int64
 49   skill_curve                  19239 non-null  int64
 50   skill_fk_accuracy            19239 non-null  int64
 51   skill_long_passing           19239 non-null  int64
 52   skill_ball_control           19239 non-null  int64
 53   movement_acceleration        19239 non-null  int64
 54   movement_sprint_speed        19239 non-null  int64
 55   movement_agility             19239 non-null  int64
 56   movement_reactions           19239 non-null  int64
 57   movement_balance             19239 non-null  int64
 58   power_shot_power             19239 non-null  int64
 59   power_jumping                19239 non-null  int64
 60   power_stamina                19239 non-null  int64
 61   power_strength               19239 non-null  int64
 62   power_long_shots             19239 non-null  int64
 63   mentality_aggression         19239 non-null  int64
 64   mentality_interceptions      19239 non-null  int64
 65   mentality_positioning        19239 non-null  int64
 66   mentality_vision             19239 non-null  int64
 67   mentality_penalties          19239 non-null  int64
 68   mentality_composure          19239 non-null  int64
 69   defending_marking_awareness  19239 non-null  int64
 70   defending_standing_tackle    19239 non-null  int64
 71   defending_sliding_tackle     19239 non-null  int64
 72   goalkeeping_diving           19239 non-null  int64
 73   goalkeeping_handling         19239 non-null  int64
 74   goalkeeping_kicking          19239 non-null  int64
 75   goalkeeping_positioning      19239 non-null  int64
 76   goalkeeping_reflexes         19239 non-null  int64
 77   goalkeeping_speed            2132 non-null   float64
 78   ls                           19239 non-null  str
 79   st                           19239 non-null  str
 80   rs                           19239 non-null  str
 81   lw                           19239 non-null  str
 82   lf                           19239 non-null  str
 83   cf                           19239 non-null  str
 84   rf                           19239 non-null  str
 85   rw                           19239 non-null  str
 86   lam                          19239 non-null  str
 87   cam                          19239 non-null  str
 88   ram                          19239 non-null  str
 89   lm                           19239 non-null  str
 90   lcm                          19239 non-null  str
 91   cm                           19239 non-null  str
 92   rcm                          19239 non-null  str
 93   rm                           19239 non-null  str
 94   lwb                          19239 non-null  str
 95   ldm                          19239 non-null  str
 96   cdm                          19239 non-null  str
 97   rdm                          19239 non-null  str
 98   rwb                          19239 non-null  str
 99   lb                           19239 non-null  str
 100  lcb                          19239 non-null  str
 101  cb                           19239 non-null  str
 102  rcb                          19239 non-null  str
 103  rb                           19239 non-null  str
 104  gk                           19239 non-null  str
 105  player_face_url              19239 non-null  str
 106  club_logo_url                19178 non-null  str
 107  club_flag_url                19178 non-null  str
 108  nation_logo_url              759 non-null    str
 109  nation_flag_url              19239 non-null  str
dtypes: float64(16), int64(44), str(50)
memory usage: 24.7 MB

In [15]:
df_22 = players_22[["short_name", "player_positions", "overall", "potential",
                   "value_eur", "age", "club_name", "league_name", "nationality_name",
                   "preferred_foot", "pace", "shooting", "passing", "dribbling",
                   "defending", "physic"]]

In [17]:
df_22

,short_name,player_positions,overall,potential,value_eur,age,club_name,league_name,nationality_name,preferred_foot,pace,shooting,passing,dribbling,defending,physic
0,L. Messi,"RW, ST, CF",93,93,78000000.0,34,Paris Saint-Germain,French Ligue 1,Argentina,Left,85.0,92.0,91.0,95.0,34.0,65.0
1,R. Lewandowski,ST,92,92,119500000.0,32,FC Bayern München,German 1. Bundesliga,Poland,Right,78.0,92.0,79.0,86.0,44.0,82.0
2,Cristiano Ronaldo,"ST, LW",91,91,45000000.0,36,Manchester United,English Premier League,Portugal,Right,87.0,94.0,80.0,88.0,34.0,75.0
3,Neymar Jr,"LW, CAM",91,91,129000000.0,29,Paris Saint-Germain,French Ligue 1,Brazil,Right,91.0,83.0,86.0,94.0,37.0,63.0
4,K. De Bruyne,"CM, CAM",91,91,125500000.0,30,Manchester City,English Premier League,Belgium,Right,76.0,86.0,93.0,88.0,64.0,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,Song Defu,CDM,47,52,70000.0,22,Wuhan FC,Chinese Super League,China PR,Right,58.0,35.0,46.0,48.0,42.0,49.0
19235,C. Porter,CM,47,59,110000.0,19,Derry City,Rep. Ireland Airtricity League,Republic of Ireland,Right,59.0,39.0,50.0,46.0,41.0,51.0
19236,N. Logue,CM,47,55,100000.0,21,Finn Harps,Rep. Ireland Airtricity League,Republic of Ireland,Right,60.0,37.0,45.0,49.0,41.0,52.0
19237,L. Rudden,ST,47,60,110000.0,19,Finn Harps,Rep. Ireland Airtricity League,Republic of Ireland,Right,68.0,46.0,36.0,48.0,15.0,42.0
19238,E. Lalchhanchhuaha,CAM,47,60,110000.0,19,NorthEast United FC,Indian Super League,India,Right,68.0,38.0,45.0,48.0,36.0,48.0

In [18]:
df_22.info()

<class 'pandas.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   short_name        19239 non-null  str
 1   player_positions  19239 non-null  str
 2   overall           19239 non-null  int64
 3   potential         19239 non-null  int64
 4   value_eur         19165 non-null  float64
 5   age               19239 non-null  int64
 6   club_name         19178 non-null  str
 7   league_name       19178 non-null  str
 8   nationality_name  19239 non-null  str
 9   preferred_foot    19239 non-null  str
 10  pace              17107 non-null  float64
 11  shooting          17107 non-null  float64
 12  passing           17107 non-null  float64
 13  dribbling         17107 non-null  float64
 14  defending         17107 non-null  float64
 15  physic            17107 non-null  float64
dtypes: float64(7), int64(3), str(6)
memory usage: 3.5 MB

In [19]:
df_22.isnull().sum()

short_name             0
player_positions       0
overall                0
potential              0
value_eur             74
age                    0
club_name             61
league_name           61
nationality_name       0
preferred_foot         0
pace                2132
shooting            2132
passing             2132
dribbling           2132
defending           2132
physic              2132
dtype: int64

In [20]:
df_limpio_22 = df_22.dropna()

In [21]:
df_limpio_22.isnull().sum()

short_name          0
player_positions    0
overall             0
potential           0
value_eur           0
age                 0
club_name           0
league_name         0
nationality_name    0
preferred_foot      0
pace                0
shooting            0
passing             0
dribbling           0
defending           0
physic              0
dtype: int64

In [22]:
df_limpio_22.info()

<class 'pandas.DataFrame'>
Index: 17041 entries, 0 to 19238
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   short_name        17041 non-null  str
 1   player_positions  17041 non-null  str
 2   overall           17041 non-null  int64
 3   potential         17041 non-null  int64
 4   value_eur         17041 non-null  float64
 5   age               17041 non-null  int64
 6   club_name         17041 non-null  str
 7   league_name       17041 non-null  str
 8   nationality_name  17041 non-null  str
 9   preferred_foot    17041 non-null  str
 10  pace              17041 non-null  float64
 11  shooting          17041 non-null  float64
 12  passing           17041 non-null  float64
 13  dribbling         17041 non-null  float64
 14  defending         17041 non-null  float64
 15  physic            17041 non-null  float64
dtypes: float64(7), int64(3), str(6)
memory usage: 3.3 MB